# Generated by Django 4.0.1 on 2022-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Monde', 'monde'), ('Moi', 'moi')], default='moi', max_length=5),
        ),
    ]
