# Generated by Django 4.0.1 on 2022-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Moi', 'moi'), ('Monde', 'monde')], default='moi', max_length=5),
        ),
    ]
