# Generated by Django 4.0.1 on 2022-02-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_alter_comment_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
