# Generated by Django 4.0.1 on 2022-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_author_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Moi', 'moi'), ('Monde', 'monde')], default='Monde', max_length=5),
        ),
    ]
